[package]
name = "emojeez"
version = "0.1.0"
authors = ["mpa <cat@snejugal.ru>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
regex = "1.4"
lazy_static = "1.4"

reqwest = "0.10"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
cached = "0.22.0"
