name: 💖 Deploy emojeez 💘

on:
  push:
    branches:
      - master


jobs:
  push_then_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        run: |
          docker login -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }} \
          docker.pkg.github.com
      - name: Pulling cache
        run: |
          docker pull docker.pkg.github.com/${{ github.repository }}/emojeez:latest || true
      - name: Build staging image
        run: |
          docker build \
            --tag docker.pkg.github.com/${{ github.repository }}/emojeez:latest \
            --cache-from docker.pkg.github.com/${{ github.repository }}/emojeez:latest \
            --file Dockerfile \
            .
      - name: Push staging image
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/emojeez:latest

      - name: Call Deploy Hooks
        run: |
          .github/deploy.sh ${{ secrets.DEPLOY_HOOK }}
