name: 💖 Deploy emojeez 💘

on:
  push:
    branches:
      - master
      - portainer-deploy # todo remove it 

jobs:
  push_then_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        run: |
          docker login -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }} \
          docker.pkg.github.com

      - name: Pulling cache
        run: |
          docker pull docker.pkg.github.com/${{ github.repository }}/emojeez:latest || true

      - name: Build staging image
        run: |
          docker build \
            --tag docker.pkg.github.com/${{ github.repository }}/emojeez:latest \
            --cache-from docker.pkg.github.com/${{ github.repository }}/emojeez:latest \
            --file Dockerfile \
            .
      - name: Push staging image
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/emojeez:latest

      - name: Deploy Stack
        uses: bots-house/portainer-deploy-stack-action@main # TODO: replace with release
        with:
          # url of Poratainer instance
          portainer-url: ${{ secrets.CLUSTER_PORTAINER_URL }}

          # portainer auth
          portainer-username: ${{ secrets.CLUSTER_PORTAINER_USERNAME }}
          portainer-password: ${{ secrets.CLUSTER_PORTAINER_PASSWORD }}
          
          # internal portainer cluster id
          portainer-endpoint: 1
          
          # stack name
          stack-name: emojeez

          # docker stack file location
          stack-file: .github/stack/production.yml
          
          # vars to substitute in stack
          stack-vars: |
            DOMAIN: emoji.${{ secrets.CLUSTER_BASE_DOMAIN }}

          # grant access for specified teams
          teams: Microservices
